# Sam note: this action is from: https://github.com/jidicula/clang-format-action

name: clang-format Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'src'
          - 'utilities'
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@v3.4.0
      with:
        clang-format-version: '11'
        check-path: ${{ matrix.path }}
        fallback-style: 'Mozilla' # optional
